version: '3.4'

services:
  productdb:
    image: mcr.microsoft.com/mssql/server:2017-latest
  
  elasticsearch:  
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.7

  dotnet.monitoring.api:
    image: ${DOCKER_REGISTRY-}dotnetmonitoringapi
    build:
      context: .
      dockerfile: src/DotNet.Monitoring.Api/Dockerfile
